apiVersion: v1
kind: Pod
metadata:
  name: log-daemon
spec:
  volumes:
    - name: nfs-mount
      persistentVolumeClaim:
        claimName: nfs-pvc-example
  containers:
  - name: container-name
    image: myyrakle/log-daemon-for-test
    volumeMounts:
      - name: nfs-mount
        mountPath: /var/log/nodejs
