apiVersion: v1
kind: PersistentVolume
metadata:                                              labels:
    app.kubernetes.io/component: single-binary           app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki

  name: nfs-pv-loki
  namespace: loki
spec:
  storageClassName: nfs
  capacity:                                              storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: /home/nfs/loki
