apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: influx
    app.kubernetes.io/name: influxdb2
  name: nfs-pv-influx
  namespace: default
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi                                      volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.2
    path: /home/nfs/influx
